name:                reddup
version:             0.1.0.0
github:              "JoelMcCracken/reddup"
license:             BSD3
author:              "Joel N. McCraken"
maintainer:          "mccracken.joel@gmail.com"
copyright:           "2018 Joel N. McCracken"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JoelMcCracken/reddup#readme>

dependencies:
- base >= 4.7 && < 5
- exceptions

library:
  source-dirs:
    - src
  dependencies:
    - raw-strings-qq
    - turtle
    - text >= 1.2.1
    - directory >= 1.2.2.0
    - unix >= 2.7.1
    - parsec
    - process
    - containers
    - foldl >= 1.2.1
    - yaml >= 0.8.22
    - bytestring >= 0.10.6
    - mtl

executables:
  reddup:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reddup
    - turtle
    - text
    - bytestring >= 0.10.6
    - mtl

tests:
  reddup-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - reddup
